//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreguntaCrearPersona {
            get {
                return ((bool)(this["PreguntaCrearPersona"]));
            }
            set {
                this["PreguntaCrearPersona"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$#,0")]
        public string FormatoPlata {
            get {
                return ((string)(this["FormatoPlata"]));
            }
            set {
                this["FormatoPlata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double MaxMin {
            get {
                return ((double)(this["MaxMin"]));
            }
            set {
                this["MaxMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string CompraFontFamily {
            get {
                return ((string)(this["CompraFontFamily"]));
            }
            set {
                this["CompraFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public float CompraFontSize {
            get {
                return ((float)(this["CompraFontSize"]));
            }
            set {
                this["CompraFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float CompraLogoProp {
            get {
                return ((float)(this["CompraLogoProp"]));
            }
            set {
                this["CompraLogoProp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public float CompraQrProp {
            get {
                return ((float)(this["CompraQrProp"]));
            }
            set {
                this["CompraQrProp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string CompraGraciasFamily {
            get {
                return ((string)(this["CompraGraciasFamily"]));
            }
            set {
                this["CompraGraciasFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public float CompraGraciasSize {
            get {
                return ((float)(this["CompraGraciasSize"]));
            }
            set {
                this["CompraGraciasSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gracias por su visita")]
        public string CompraGraciasText {
            get {
                return ((string)(this["CompraGraciasText"]));
            }
            set {
                this["CompraGraciasText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"En La Serena a [fecha]
Nombre: [nombre] [apellido]
Cedula de identidad N°: [rut]
Correo Electrónico: [email]

1.- Ser mayor de edad y contar con las aptitudes físicas y de salud necesarias para jugar en el Paintball/MTB/Muro de escalada, existente en área especial de Las Tacas.

2.- Conocer el riesgo de la actividad a desarrollar y hacer decidido libre y espontáneamente mi participación, bajo mi exclusiva responsabilidad.

3.- Comprometerme a utilizar en todo momento los elementes de seguridad proporcionados por la entidad a cargo de la actividad: casco, arnés, cinta y mosquetones.
Vaciar todos mis bolsillos u otras cosas que puedan caer al vacio, dañando a terceras personas o parte de DistritoAventura. Si ocurriese lo contrario lo que produjera un accidente, me comprometo a cubrir con los gastos y daños ocurridos.

4.- Conocer y aceptar que DistritoAventura y Las Tacas quedan eximidos de toda responsabilidad frente a cualquier accidente o daño que se produzca o sufra como consecuencia de mi participación o utilización del juego Paintball/MTB/Muro de escalada indicado más arriba.")]
        public string ContratoTexto {
            get {
                return ((string)(this["ContratoTexto"]));
            }
            set {
                this["ContratoTexto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana")]
        public string ContratoFamily {
            get {
                return ((string)(this["ContratoFamily"]));
            }
            set {
                this["ContratoFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public float ContratoSize {
            get {
                return ((float)(this["ContratoSize"]));
            }
            set {
                this["ContratoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PersonaPrintDialog {
            get {
                return ((bool)(this["PersonaPrintDialog"]));
            }
            set {
                this["PersonaPrintDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompraPrintDialog {
            get {
                return ((bool)(this["CompraPrintDialog"]));
            }
            set {
                this["CompraPrintDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GmailUser {
            get {
                return ((string)(this["GmailUser"]));
            }
            set {
                this["GmailUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GmailPass {
            get {
                return ((string)(this["GmailPass"]));
            }
            set {
                this["GmailPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avelinosalas@gmail.com,felipeortegabustamante@gmail.com")]
        public string GmailTo {
            get {
                return ((string)(this["GmailTo"]));
            }
            set {
                this["GmailTo"] = value;
            }
        }
    }
}
