//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_Compra_Persona", "Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Persona), "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.Compra), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_ItemCompra_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Compra), "ItemCompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.ItemCompra), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_PagoEfectivo_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Compra), "PagoEfectivo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.PagoEfectivo), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_PagoPrepago_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Compra), "PagoPrepago", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.PagoPrepago), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_PagoRedcompra_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Compra), "PagoRedcompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.PagoRedcompra), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_ItemCompra_Item", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Item), "ItemCompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.ItemCompra), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_PagoPrepago_Prepago", "Prepago", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Prepago), "PagoPrepago", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.PagoPrepago), true)]

#endregion

namespace POS
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB object using the connection string found in the 'DB' section of the application configuration file.
        /// </summary>
        public DB() : base("name=DB", "DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB object.
        /// </summary>
        public DB(string connectionString) : base(connectionString, "DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB object.
        /// </summary>
        public DB(EntityConnection connection) : base(connection, "DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Compra> Compras
        {
            get
            {
                if ((_Compras == null))
                {
                    _Compras = base.CreateObjectSet<Compra>("Compras");
                }
                return _Compras;
            }
        }
        private ObjectSet<Compra> _Compras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemCompra> ItemsCompra
        {
            get
            {
                if ((_ItemsCompra == null))
                {
                    _ItemsCompra = base.CreateObjectSet<ItemCompra>("ItemsCompra");
                }
                return _ItemsCompra;
            }
        }
        private ObjectSet<ItemCompra> _ItemsCompra;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PagoEfectivo> PagosEfectivo
        {
            get
            {
                if ((_PagosEfectivo == null))
                {
                    _PagosEfectivo = base.CreateObjectSet<PagoEfectivo>("PagosEfectivo");
                }
                return _PagosEfectivo;
            }
        }
        private ObjectSet<PagoEfectivo> _PagosEfectivo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PagoPrepago> PagosPrepago
        {
            get
            {
                if ((_PagosPrepago == null))
                {
                    _PagosPrepago = base.CreateObjectSet<PagoPrepago>("PagosPrepago");
                }
                return _PagosPrepago;
            }
        }
        private ObjectSet<PagoPrepago> _PagosPrepago;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PagoRedcompra> PagosRedcompra
        {
            get
            {
                if ((_PagosRedcompra == null))
                {
                    _PagosRedcompra = base.CreateObjectSet<PagoRedcompra>("PagosRedcompra");
                }
                return _PagosRedcompra;
            }
        }
        private ObjectSet<PagoRedcompra> _PagosRedcompra;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Persona> Personas
        {
            get
            {
                if ((_Personas == null))
                {
                    _Personas = base.CreateObjectSet<Persona>("Personas");
                }
                return _Personas;
            }
        }
        private ObjectSet<Persona> _Personas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prepago> Prepagos
        {
            get
            {
                if ((_Prepagos == null))
                {
                    _Prepagos = base.CreateObjectSet<Prepago>("Prepagos");
                }
                return _Prepagos;
            }
        }
        private ObjectSet<Prepago> _Prepagos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ComprasDetalle> ComprasDetalle
        {
            get
            {
                if ((_ComprasDetalle == null))
                {
                    _ComprasDetalle = base.CreateObjectSet<ComprasDetalle>("ComprasDetalle");
                }
                return _ComprasDetalle;
            }
        }
        private ObjectSet<ComprasDetalle> _ComprasDetalle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ComprasDiaria> ComprasDiaria
        {
            get
            {
                if ((_ComprasDiaria == null))
                {
                    _ComprasDiaria = base.CreateObjectSet<ComprasDiaria>("ComprasDiaria");
                }
                return _ComprasDiaria;
            }
        }
        private ObjectSet<ComprasDiaria> _ComprasDiaria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemCompraDetalle> ItemCompraDetalle
        {
            get
            {
                if ((_ItemCompraDetalle == null))
                {
                    _ItemCompraDetalle = base.CreateObjectSet<ItemCompraDetalle>("ItemCompraDetalle");
                }
                return _ItemCompraDetalle;
            }
        }
        private ObjectSet<ItemCompraDetalle> _ItemCompraDetalle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemCompraDiaria> ItemCompraDiaria
        {
            get
            {
                if ((_ItemCompraDiaria == null))
                {
                    _ItemCompraDiaria = base.CreateObjectSet<ItemCompraDiaria>("ItemCompraDiaria");
                }
                return _ItemCompraDiaria;
            }
        }
        private ObjectSet<ItemCompraDiaria> _ItemCompraDiaria;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Compras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompras(Compra compra)
        {
            base.AddObject("Compras", compra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemsCompra EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemsCompra(ItemCompra itemCompra)
        {
            base.AddObject("ItemsCompra", itemCompra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PagosEfectivo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagosEfectivo(PagoEfectivo pagoEfectivo)
        {
            base.AddObject("PagosEfectivo", pagoEfectivo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PagosPrepago EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagosPrepago(PagoPrepago pagoPrepago)
        {
            base.AddObject("PagosPrepago", pagoPrepago);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PagosRedcompra EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagosRedcompra(PagoRedcompra pagoRedcompra)
        {
            base.AddObject("PagosRedcompra", pagoRedcompra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Personas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPersonas(Persona persona)
        {
            base.AddObject("Personas", persona);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Prepagos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrepagos(Prepago prepago)
        {
            base.AddObject("Prepagos", prepago);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ComprasDetalle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComprasDetalle(ComprasDetalle comprasDetalle)
        {
            base.AddObject("ComprasDetalle", comprasDetalle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ComprasDiaria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComprasDiaria(ComprasDiaria comprasDiaria)
        {
            base.AddObject("ComprasDiaria", comprasDiaria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemCompraDetalle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemCompraDetalle(ItemCompraDetalle itemCompraDetalle)
        {
            base.AddObject("ItemCompraDetalle", itemCompraDetalle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemCompraDiaria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemCompraDiaria(ItemCompraDiaria itemCompraDiaria)
        {
            base.AddObject("ItemCompraDiaria", itemCompraDiaria);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="Compra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Compra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Compra object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="personaID">Initial value of the PersonaID property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        public static Compra CreateCompra(global::System.Int64 id, global::System.Int32 personaID, global::System.Int32 total, global::System.DateTime fecha)
        {
            Compra compra = new Compra();
            compra.ID = id;
            compra.PersonaID = personaID;
            compra.Total = total;
            compra.Fecha = fecha;
            return compra;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonaID
        {
            get
            {
                return _PersonaID;
            }
            set
            {
                OnPersonaIDChanging(value);
                ReportPropertyChanging("PersonaID");
                _PersonaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonaID");
                OnPersonaIDChanged();
            }
        }
        private global::System.Int32 _PersonaID;
        partial void OnPersonaIDChanging(global::System.Int32 value);
        partial void OnPersonaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Int32 _Total;
        partial void OnTotalChanging(global::System.Int32 value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            internal set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_Compra_Persona", "Persona")]
        public Persona Persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("LasTacasModel.FK_Compra_Persona", "Persona").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("LasTacasModel.FK_Compra_Persona", "Persona").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persona> PersonaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("LasTacasModel.FK_Compra_Persona", "Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persona>("LasTacasModel.FK_Compra_Persona", "Persona", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_ItemCompra_Compra", "ItemCompra")]
        public EntityCollection<ItemCompra> Items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemCompra>("LasTacasModel.FK_ItemCompra_Compra", "ItemCompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemCompra>("LasTacasModel.FK_ItemCompra_Compra", "ItemCompra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoEfectivo_Compra", "PagoEfectivo")]
        public EntityCollection<PagoEfectivo> PagoEfectivo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoEfectivo>("LasTacasModel.FK_PagoEfectivo_Compra", "PagoEfectivo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoEfectivo>("LasTacasModel.FK_PagoEfectivo_Compra", "PagoEfectivo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoPrepago_Compra", "PagoPrepago")]
        public EntityCollection<PagoPrepago> PagoPrepago
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoPrepago>("LasTacasModel.FK_PagoPrepago_Compra", "PagoPrepago");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoPrepago>("LasTacasModel.FK_PagoPrepago_Compra", "PagoPrepago", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoRedcompra_Compra", "PagoRedcompra")]
        public EntityCollection<PagoRedcompra> PagoRedcompra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoRedcompra>("LasTacasModel.FK_PagoRedcompra_Compra", "PagoRedcompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoRedcompra>("LasTacasModel.FK_PagoRedcompra_Compra", "PagoRedcompra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="ComprasDetalle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ComprasDetalle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ComprasDetalle object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="fecha">Initial value of the fecha property.</param>
        /// <param name="rut">Initial value of the rut property.</param>
        /// <param name="apellido">Initial value of the apellido property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="total">Initial value of the total property.</param>
        public static ComprasDetalle CreateComprasDetalle(global::System.Int64 id, global::System.DateTime fecha, global::System.String rut, global::System.String apellido, global::System.String nombre, global::System.Int32 total)
        {
            ComprasDetalle comprasDetalle = new ComprasDetalle();
            comprasDetalle.id = id;
            comprasDetalle.fecha = fecha;
            comprasDetalle.rut = rut;
            comprasDetalle.apellido = apellido;
            comprasDetalle.nombre = nombre;
            comprasDetalle.total = total;
            return comprasDetalle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rut
        {
            get
            {
                return _rut;
            }
            set
            {
                if (_rut != value)
                {
                    OnrutChanging(value);
                    ReportPropertyChanging("rut");
                    _rut = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("rut");
                    OnrutChanged();
                }
            }
        }
        private global::System.String _rut;
        partial void OnrutChanging(global::System.String value);
        partial void OnrutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                if (_apellido != value)
                {
                    OnapellidoChanging(value);
                    ReportPropertyChanging("apellido");
                    _apellido = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("apellido");
                    OnapellidoChanged();
                }
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                if (_nombre != value)
                {
                    OnnombreChanging(value);
                    ReportPropertyChanging("nombre");
                    _nombre = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nombre");
                    OnnombreChanged();
                }
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechanacimiento
        {
            get
            {
                return _fechanacimiento;
            }
            set
            {
                OnfechanacimientoChanging(value);
                ReportPropertyChanging("fechanacimiento");
                _fechanacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechanacimiento");
                OnfechanacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechanacimiento;
        partial void OnfechanacimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnfechanacimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 total
        {
            get
            {
                return _total;
            }
            set
            {
                if (_total != value)
                {
                    OntotalChanging(value);
                    ReportPropertyChanging("total");
                    _total = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("total");
                    OntotalChanged();
                }
            }
        }
        private global::System.Int32 _total;
        partial void OntotalChanging(global::System.Int32 value);
        partial void OntotalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="ComprasDiaria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ComprasDiaria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ComprasDiaria object.
        /// </summary>
        /// <param name="efectivo">Initial value of the Efectivo property.</param>
        /// <param name="redCompra">Initial value of the RedCompra property.</param>
        /// <param name="prePago">Initial value of the PrePago property.</param>
        public static ComprasDiaria CreateComprasDiaria(global::System.Int32 efectivo, global::System.Int32 redCompra, global::System.Int32 prePago)
        {
            ComprasDiaria comprasDiaria = new ComprasDiaria();
            comprasDiaria.Efectivo = efectivo;
            comprasDiaria.RedCompra = redCompra;
            comprasDiaria.PrePago = prePago;
            return comprasDiaria;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Dia
        {
            get
            {
                return _Dia;
            }
            set
            {
                OnDiaChanging(value);
                ReportPropertyChanging("Dia");
                _Dia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dia");
                OnDiaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Dia;
        partial void OnDiaChanging(Nullable<global::System.DateTime> value);
        partial void OnDiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Efectivo
        {
            get
            {
                return _Efectivo;
            }
            set
            {
                if (_Efectivo != value)
                {
                    OnEfectivoChanging(value);
                    ReportPropertyChanging("Efectivo");
                    _Efectivo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Efectivo");
                    OnEfectivoChanged();
                }
            }
        }
        private global::System.Int32 _Efectivo;
        partial void OnEfectivoChanging(global::System.Int32 value);
        partial void OnEfectivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RedCompra
        {
            get
            {
                return _RedCompra;
            }
            set
            {
                if (_RedCompra != value)
                {
                    OnRedCompraChanging(value);
                    ReportPropertyChanging("RedCompra");
                    _RedCompra = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RedCompra");
                    OnRedCompraChanged();
                }
            }
        }
        private global::System.Int32 _RedCompra;
        partial void OnRedCompraChanging(global::System.Int32 value);
        partial void OnRedCompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PrePago
        {
            get
            {
                return _PrePago;
            }
            set
            {
                if (_PrePago != value)
                {
                    OnPrePagoChanging(value);
                    ReportPropertyChanging("PrePago");
                    _PrePago = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PrePago");
                    OnPrePagoChanged();
                }
            }
        }
        private global::System.Int32 _PrePago;
        partial void OnPrePagoChanging(global::System.Int32 value);
        partial void OnPrePagoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Num
        {
            get
            {
                return _Num;
            }
            set
            {
                OnNumChanging(value);
                ReportPropertyChanging("Num");
                _Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Num");
                OnNumChanged();
            }
        }
        private Nullable<global::System.Int32> _Num;
        partial void OnNumChanging(Nullable<global::System.Int32> value);
        partial void OnNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        /// <param name="activo">Initial value of the Activo property.</param>
        public static Item CreateItem(global::System.Int32 id, global::System.String nombre, global::System.Int32 valor, global::System.Boolean activo)
        {
            Item item = new Item();
            item.ID = id;
            item.Nombre = nombre;
            item.Valor = valor;
            item.Activo = activo;
            return item;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_ItemCompra_Item", "ItemCompra")]
        public EntityCollection<ItemCompra> Compras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemCompra>("LasTacasModel.FK_ItemCompra_Item", "ItemCompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemCompra>("LasTacasModel.FK_ItemCompra_Item", "ItemCompra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="ItemCompra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemCompra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemCompra object.
        /// </summary>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        /// <param name="cantidad">Initial value of the Cantidad property.</param>
        public static ItemCompra CreateItemCompra(global::System.Int64 compraID, global::System.Int32 itemID, global::System.Int32 valor, global::System.Byte cantidad)
        {
            ItemCompra itemCompra = new ItemCompra();
            itemCompra.CompraID = compraID;
            itemCompra.ItemID = itemID;
            itemCompra.Valor = valor;
            itemCompra.Cantidad = cantidad;
            return itemCompra;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                if (_CompraID != value)
                {
                    OnCompraIDChanging(value);
                    ReportPropertyChanging("CompraID");
                    _CompraID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CompraID");
                    OnCompraIDChanged();
                }
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Int32 _ItemID;
        partial void OnItemIDChanging(global::System.Int32 value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Byte _Cantidad;
        partial void OnCantidadChanging(global::System.Byte value);
        partial void OnCantidadChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_ItemCompra_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_ItemCompra_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_ItemCompra_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_ItemCompra_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("LasTacasModel.FK_ItemCompra_Compra", "Compra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_ItemCompra_Item", "Item")]
        public Item Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("LasTacasModel.FK_ItemCompra_Item", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("LasTacasModel.FK_ItemCompra_Item", "Item").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("LasTacasModel.FK_ItemCompra_Item", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("LasTacasModel.FK_ItemCompra_Item", "Item", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="ItemCompraDetalle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemCompraDetalle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemCompraDetalle object.
        /// </summary>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="fechaCompra">Initial value of the FechaCompra property.</param>
        /// <param name="item">Initial value of the Item property.</param>
        /// <param name="valorItemUnitario">Initial value of the ValorItemUnitario property.</param>
        /// <param name="cantidad">Initial value of the Cantidad property.</param>
        public static ItemCompraDetalle CreateItemCompraDetalle(global::System.Int64 compraID, global::System.DateTime fechaCompra, global::System.String item, global::System.Int32 valorItemUnitario, global::System.Byte cantidad)
        {
            ItemCompraDetalle itemCompraDetalle = new ItemCompraDetalle();
            itemCompraDetalle.CompraID = compraID;
            itemCompraDetalle.FechaCompra = fechaCompra;
            itemCompraDetalle.Item = item;
            itemCompraDetalle.ValorItemUnitario = valorItemUnitario;
            itemCompraDetalle.Cantidad = cantidad;
            return itemCompraDetalle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                if (_CompraID != value)
                {
                    OnCompraIDChanging(value);
                    ReportPropertyChanging("CompraID");
                    _CompraID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CompraID");
                    OnCompraIDChanged();
                }
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCompra
        {
            get
            {
                return _FechaCompra;
            }
            set
            {
                if (_FechaCompra != value)
                {
                    OnFechaCompraChanging(value);
                    ReportPropertyChanging("FechaCompra");
                    _FechaCompra = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FechaCompra");
                    OnFechaCompraChanged();
                }
            }
        }
        private global::System.DateTime _FechaCompra;
        partial void OnFechaCompraChanging(global::System.DateTime value);
        partial void OnFechaCompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Item
        {
            get
            {
                return _Item;
            }
            set
            {
                if (_Item != value)
                {
                    OnItemChanging(value);
                    ReportPropertyChanging("Item");
                    _Item = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Item");
                    OnItemChanged();
                }
            }
        }
        private global::System.String _Item;
        partial void OnItemChanging(global::System.String value);
        partial void OnItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ValorItemUnitario
        {
            get
            {
                return _ValorItemUnitario;
            }
            set
            {
                if (_ValorItemUnitario != value)
                {
                    OnValorItemUnitarioChanging(value);
                    ReportPropertyChanging("ValorItemUnitario");
                    _ValorItemUnitario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ValorItemUnitario");
                    OnValorItemUnitarioChanged();
                }
            }
        }
        private global::System.Int32 _ValorItemUnitario;
        partial void OnValorItemUnitarioChanging(global::System.Int32 value);
        partial void OnValorItemUnitarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                if (_Cantidad != value)
                {
                    OnCantidadChanging(value);
                    ReportPropertyChanging("Cantidad");
                    _Cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cantidad");
                    OnCantidadChanged();
                }
            }
        }
        private global::System.Byte _Cantidad;
        partial void OnCantidadChanging(global::System.Byte value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ValorItemTotal
        {
            get
            {
                return _ValorItemTotal;
            }
            set
            {
                OnValorItemTotalChanging(value);
                ReportPropertyChanging("ValorItemTotal");
                _ValorItemTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValorItemTotal");
                OnValorItemTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _ValorItemTotal;
        partial void OnValorItemTotalChanging(Nullable<global::System.Int32> value);
        partial void OnValorItemTotalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="ItemCompraDiaria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemCompraDiaria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemCompraDiaria object.
        /// </summary>
        /// <param name="item">Initial value of the Item property.</param>
        public static ItemCompraDiaria CreateItemCompraDiaria(global::System.String item)
        {
            ItemCompraDiaria itemCompraDiaria = new ItemCompraDiaria();
            itemCompraDiaria.Item = item;
            return itemCompraDiaria;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Dia
        {
            get
            {
                return _Dia;
            }
            set
            {
                OnDiaChanging(value);
                ReportPropertyChanging("Dia");
                _Dia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dia");
                OnDiaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Dia;
        partial void OnDiaChanging(Nullable<global::System.DateTime> value);
        partial void OnDiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Item
        {
            get
            {
                return _Item;
            }
            set
            {
                if (_Item != value)
                {
                    OnItemChanging(value);
                    ReportPropertyChanging("Item");
                    _Item = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Item");
                    OnItemChanged();
                }
            }
        }
        private global::System.String _Item;
        partial void OnItemChanging(global::System.String value);
        partial void OnItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Num
        {
            get
            {
                return _Num;
            }
            set
            {
                OnNumChanging(value);
                ReportPropertyChanging("Num");
                _Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Num");
                OnNumChanged();
            }
        }
        private Nullable<global::System.Int32> _Num;
        partial void OnNumChanging(Nullable<global::System.Int32> value);
        partial void OnNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="PagoEfectivo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoEfectivo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PagoEfectivo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        public static PagoEfectivo CreatePagoEfectivo(global::System.Int32 id, global::System.Int64 compraID, global::System.Int32 valor)
        {
            PagoEfectivo pagoEfectivo = new PagoEfectivo();
            pagoEfectivo.ID = id;
            pagoEfectivo.CompraID = compraID;
            pagoEfectivo.Valor = valor;
            return pagoEfectivo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                OnCompraIDChanging(value);
                ReportPropertyChanging("CompraID");
                _CompraID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompraID");
                OnCompraIDChanged();
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoEfectivo_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoEfectivo_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoEfectivo_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoEfectivo_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("LasTacasModel.FK_PagoEfectivo_Compra", "Compra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="PagoPrepago")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoPrepago : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PagoPrepago object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="prepagoID">Initial value of the PrepagoID property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        public static PagoPrepago CreatePagoPrepago(global::System.Int32 id, global::System.Int64 compraID, global::System.Int32 prepagoID, global::System.Int32 valor)
        {
            PagoPrepago pagoPrepago = new PagoPrepago();
            pagoPrepago.ID = id;
            pagoPrepago.CompraID = compraID;
            pagoPrepago.PrepagoID = prepagoID;
            pagoPrepago.Valor = valor;
            return pagoPrepago;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                OnCompraIDChanging(value);
                ReportPropertyChanging("CompraID");
                _CompraID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompraID");
                OnCompraIDChanged();
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PrepagoID
        {
            get
            {
                return _PrepagoID;
            }
            set
            {
                OnPrepagoIDChanging(value);
                ReportPropertyChanging("PrepagoID");
                _PrepagoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrepagoID");
                OnPrepagoIDChanged();
            }
        }
        private global::System.Int32 _PrepagoID;
        partial void OnPrepagoIDChanging(global::System.Int32 value);
        partial void OnPrepagoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoPrepago_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoPrepago_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoPrepago_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoPrepago_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("LasTacasModel.FK_PagoPrepago_Compra", "Compra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoPrepago_Prepago", "Prepago")]
        public Prepago Prepago
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prepago>("LasTacasModel.FK_PagoPrepago_Prepago", "Prepago").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prepago>("LasTacasModel.FK_PagoPrepago_Prepago", "Prepago").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Prepago> PrepagoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prepago>("LasTacasModel.FK_PagoPrepago_Prepago", "Prepago");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Prepago>("LasTacasModel.FK_PagoPrepago_Prepago", "Prepago", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="PagoRedcompra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoRedcompra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PagoRedcompra object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        /// <param name="transaccion">Initial value of the Transaccion property.</param>
        /// <param name="autorizacion">Initial value of the Autorizacion property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        public static PagoRedcompra CreatePagoRedcompra(global::System.Int32 id, global::System.Int64 compraID, global::System.String tipo, global::System.Int32 transaccion, global::System.Int32 autorizacion, global::System.Int32 valor)
        {
            PagoRedcompra pagoRedcompra = new PagoRedcompra();
            pagoRedcompra.ID = id;
            pagoRedcompra.CompraID = compraID;
            pagoRedcompra.Tipo = tipo;
            pagoRedcompra.Transaccion = transaccion;
            pagoRedcompra.Autorizacion = autorizacion;
            pagoRedcompra.Valor = valor;
            return pagoRedcompra;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                OnCompraIDChanging(value);
                ReportPropertyChanging("CompraID");
                _CompraID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompraID");
                OnCompraIDChanged();
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Transaccion
        {
            get
            {
                return _Transaccion;
            }
            set
            {
                OnTransaccionChanging(value);
                ReportPropertyChanging("Transaccion");
                _Transaccion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Transaccion");
                OnTransaccionChanged();
            }
        }
        private global::System.Int32 _Transaccion;
        partial void OnTransaccionChanging(global::System.Int32 value);
        partial void OnTransaccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Autorizacion
        {
            get
            {
                return _Autorizacion;
            }
            set
            {
                OnAutorizacionChanging(value);
                ReportPropertyChanging("Autorizacion");
                _Autorizacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Autorizacion");
                OnAutorizacionChanged();
            }
        }
        private global::System.Int32 _Autorizacion;
        partial void OnAutorizacionChanging(global::System.Int32 value);
        partial void OnAutorizacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoRedcompra_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoRedcompra_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoRedcompra_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoRedcompra_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("LasTacasModel.FK_PagoRedcompra_Compra", "Compra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Persona : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Persona object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="rUT">Initial value of the RUT property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="fechaRegistro">Initial value of the FechaRegistro property.</param>
        public static Persona CreatePersona(global::System.Int32 id, global::System.String rUT, global::System.String apellido, global::System.String nombre, global::System.DateTime fechaRegistro)
        {
            Persona persona = new Persona();
            persona.ID = id;
            persona.RUT = rUT;
            persona.Apellido = apellido;
            persona.Nombre = nombre;
            persona.FechaRegistro = fechaRegistro;
            return persona;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT
        {
            get
            {
                return _RUT;
            }
            set
            {
                OnRUTChanging(value);
                ReportPropertyChanging("RUT");
                _RUT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RUT");
                OnRUTChanged();
            }
        }
        private global::System.String _RUT;
        partial void OnRUTChanging(global::System.String value);
        partial void OnRUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            internal set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private global::System.DateTime _FechaRegistro;
        partial void OnFechaRegistroChanging(global::System.DateTime value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaNacimiento
        {
            get
            {
                return _FechaNacimiento;
            }
            set
            {
                OnFechaNacimientoChanging(value);
                ReportPropertyChanging("FechaNacimiento");
                _FechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNacimiento");
                OnFechaNacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaNacimiento;
        partial void OnFechaNacimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaNacimientoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_Compra_Persona", "Compra")]
        public EntityCollection<Compra> Compras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Compra>("LasTacasModel.FK_Compra_Persona", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Compra>("LasTacasModel.FK_Compra_Persona", "Compra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="Prepago")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prepago : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Prepago object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="saldo">Initial value of the Saldo property.</param>
        public static Prepago CreatePrepago(global::System.Int32 id, global::System.Int32 saldo)
        {
            Prepago prepago = new Prepago();
            prepago.ID = id;
            prepago.Saldo = saldo;
            return prepago;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Saldo
        {
            get
            {
                return _Saldo;
            }
            set
            {
                OnSaldoChanging(value);
                ReportPropertyChanging("Saldo");
                _Saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Saldo");
                OnSaldoChanged();
            }
        }
        private global::System.Int32 _Saldo;
        partial void OnSaldoChanging(global::System.Int32 value);
        partial void OnSaldoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoPrepago_Prepago", "PagoPrepago")]
        public EntityCollection<PagoPrepago> Pagos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoPrepago>("LasTacasModel.FK_PagoPrepago_Prepago", "PagoPrepago");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoPrepago>("LasTacasModel.FK_PagoPrepago_Prepago", "PagoPrepago", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
