//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_Compra_Persona", "Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Persona), "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.Compra), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_ItemCompra_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Compra), "ItemCompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.ItemCompra), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_PagoEfectivo_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Compra), "PagoEfectivo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.PagoEfectivo), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_PagoPrepago_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Compra), "PagoPrepago", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.PagoPrepago), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_PagoRedcompra_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Compra), "PagoRedcompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.PagoRedcompra), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_ItemCompra_Item", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Item), "ItemCompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.ItemCompra), true)]
[assembly: EdmRelationshipAttribute("LasTacasModel", "FK_PagoPrepago_Prepago", "Prepago", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(POS.Prepago), "PagoPrepago", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POS.PagoPrepago), true)]

#endregion

namespace POS
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB object using the connection string found in the 'DB' section of the application configuration file.
        /// </summary>
        public DB() : base("name=DB", "DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB object.
        /// </summary>
        public DB(string connectionString) : base(connectionString, "DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB object.
        /// </summary>
        public DB(EntityConnection connection) : base(connection, "DB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Compra> Compras
        {
            get
            {
                if ((_Compras == null))
                {
                    _Compras = base.CreateObjectSet<Compra>("Compras");
                }
                return _Compras;
            }
        }
        private ObjectSet<Compra> _Compras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemCompra> ItemCompras
        {
            get
            {
                if ((_ItemCompras == null))
                {
                    _ItemCompras = base.CreateObjectSet<ItemCompra>("ItemCompras");
                }
                return _ItemCompras;
            }
        }
        private ObjectSet<ItemCompra> _ItemCompras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PagoEfectivo> PagoEfectivoes
        {
            get
            {
                if ((_PagoEfectivoes == null))
                {
                    _PagoEfectivoes = base.CreateObjectSet<PagoEfectivo>("PagoEfectivoes");
                }
                return _PagoEfectivoes;
            }
        }
        private ObjectSet<PagoEfectivo> _PagoEfectivoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PagoPrepago> PagoPrepagoes
        {
            get
            {
                if ((_PagoPrepagoes == null))
                {
                    _PagoPrepagoes = base.CreateObjectSet<PagoPrepago>("PagoPrepagoes");
                }
                return _PagoPrepagoes;
            }
        }
        private ObjectSet<PagoPrepago> _PagoPrepagoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PagoRedcompra> PagoRedcompras
        {
            get
            {
                if ((_PagoRedcompras == null))
                {
                    _PagoRedcompras = base.CreateObjectSet<PagoRedcompra>("PagoRedcompras");
                }
                return _PagoRedcompras;
            }
        }
        private ObjectSet<PagoRedcompra> _PagoRedcompras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Persona> Personas
        {
            get
            {
                if ((_Personas == null))
                {
                    _Personas = base.CreateObjectSet<Persona>("Personas");
                }
                return _Personas;
            }
        }
        private ObjectSet<Persona> _Personas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prepago> Prepagoes
        {
            get
            {
                if ((_Prepagoes == null))
                {
                    _Prepagoes = base.CreateObjectSet<Prepago>("Prepagoes");
                }
                return _Prepagoes;
            }
        }
        private ObjectSet<Prepago> _Prepagoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Compras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompras(Compra compra)
        {
            base.AddObject("Compras", compra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemCompras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemCompras(ItemCompra itemCompra)
        {
            base.AddObject("ItemCompras", itemCompra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PagoEfectivoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagoEfectivoes(PagoEfectivo pagoEfectivo)
        {
            base.AddObject("PagoEfectivoes", pagoEfectivo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PagoPrepagoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagoPrepagoes(PagoPrepago pagoPrepago)
        {
            base.AddObject("PagoPrepagoes", pagoPrepago);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PagoRedcompras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagoRedcompras(PagoRedcompra pagoRedcompra)
        {
            base.AddObject("PagoRedcompras", pagoRedcompra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Personas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPersonas(Persona persona)
        {
            base.AddObject("Personas", persona);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Prepagoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrepagoes(Prepago prepago)
        {
            base.AddObject("Prepagoes", prepago);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="Compra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Compra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Compra object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="personaID">Initial value of the PersonaID property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        public static Compra CreateCompra(global::System.Int64 id, global::System.Int32 personaID, global::System.Int64 total, global::System.DateTime fecha)
        {
            Compra compra = new Compra();
            compra.ID = id;
            compra.PersonaID = personaID;
            compra.Total = total;
            compra.Fecha = fecha;
            return compra;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonaID
        {
            get
            {
                return _PersonaID;
            }
            set
            {
                OnPersonaIDChanging(value);
                ReportPropertyChanging("PersonaID");
                _PersonaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonaID");
                OnPersonaIDChanged();
            }
        }
        private global::System.Int32 _PersonaID;
        partial void OnPersonaIDChanging(global::System.Int32 value);
        partial void OnPersonaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Int64 _Total;
        partial void OnTotalChanging(global::System.Int64 value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            internal set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_Compra_Persona", "Persona")]
        public Persona Persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("LasTacasModel.FK_Compra_Persona", "Persona").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("LasTacasModel.FK_Compra_Persona", "Persona").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persona> PersonaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("LasTacasModel.FK_Compra_Persona", "Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persona>("LasTacasModel.FK_Compra_Persona", "Persona", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_ItemCompra_Compra", "ItemCompra")]
        public EntityCollection<ItemCompra> Items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemCompra>("LasTacasModel.FK_ItemCompra_Compra", "ItemCompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemCompra>("LasTacasModel.FK_ItemCompra_Compra", "ItemCompra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoEfectivo_Compra", "PagoEfectivo")]
        public EntityCollection<PagoEfectivo> PagoEfectivo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoEfectivo>("LasTacasModel.FK_PagoEfectivo_Compra", "PagoEfectivo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoEfectivo>("LasTacasModel.FK_PagoEfectivo_Compra", "PagoEfectivo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoPrepago_Compra", "PagoPrepago")]
        public EntityCollection<PagoPrepago> PagoPrepago
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoPrepago>("LasTacasModel.FK_PagoPrepago_Compra", "PagoPrepago");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoPrepago>("LasTacasModel.FK_PagoPrepago_Compra", "PagoPrepago", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoRedcompra_Compra", "PagoRedcompra")]
        public EntityCollection<PagoRedcompra> PagoRedcompra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoRedcompra>("LasTacasModel.FK_PagoRedcompra_Compra", "PagoRedcompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoRedcompra>("LasTacasModel.FK_PagoRedcompra_Compra", "PagoRedcompra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        /// <param name="activo">Initial value of the Activo property.</param>
        public static Item CreateItem(global::System.Int32 id, global::System.String nombre, global::System.Int32 valor, global::System.Boolean activo)
        {
            Item item = new Item();
            item.ID = id;
            item.Nombre = nombre;
            item.Valor = valor;
            item.Activo = activo;
            return item;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_ItemCompra_Item", "ItemCompra")]
        public EntityCollection<ItemCompra> Compras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemCompra>("LasTacasModel.FK_ItemCompra_Item", "ItemCompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemCompra>("LasTacasModel.FK_ItemCompra_Item", "ItemCompra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="ItemCompra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemCompra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemCompra object.
        /// </summary>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        /// <param name="cantidad">Initial value of the Cantidad property.</param>
        public static ItemCompra CreateItemCompra(global::System.Int64 compraID, global::System.Int32 itemID, global::System.Int32 valor, global::System.Byte cantidad)
        {
            ItemCompra itemCompra = new ItemCompra();
            itemCompra.CompraID = compraID;
            itemCompra.ItemID = itemID;
            itemCompra.Valor = valor;
            itemCompra.Cantidad = cantidad;
            return itemCompra;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                if (_CompraID != value)
                {
                    OnCompraIDChanging(value);
                    ReportPropertyChanging("CompraID");
                    _CompraID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CompraID");
                    OnCompraIDChanged();
                }
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Int32 _ItemID;
        partial void OnItemIDChanging(global::System.Int32 value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Byte _Cantidad;
        partial void OnCantidadChanging(global::System.Byte value);
        partial void OnCantidadChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_ItemCompra_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_ItemCompra_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_ItemCompra_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_ItemCompra_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("LasTacasModel.FK_ItemCompra_Compra", "Compra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_ItemCompra_Item", "Item")]
        public Item Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("LasTacasModel.FK_ItemCompra_Item", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("LasTacasModel.FK_ItemCompra_Item", "Item").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("LasTacasModel.FK_ItemCompra_Item", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("LasTacasModel.FK_ItemCompra_Item", "Item", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="PagoEfectivo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoEfectivo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PagoEfectivo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        public static PagoEfectivo CreatePagoEfectivo(global::System.Int32 id, global::System.Int64 compraID, global::System.Int32 valor)
        {
            PagoEfectivo pagoEfectivo = new PagoEfectivo();
            pagoEfectivo.ID = id;
            pagoEfectivo.CompraID = compraID;
            pagoEfectivo.Valor = valor;
            return pagoEfectivo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                OnCompraIDChanging(value);
                ReportPropertyChanging("CompraID");
                _CompraID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompraID");
                OnCompraIDChanged();
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoEfectivo_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoEfectivo_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoEfectivo_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoEfectivo_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("LasTacasModel.FK_PagoEfectivo_Compra", "Compra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="PagoPrepago")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoPrepago : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PagoPrepago object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="prepagoID">Initial value of the PrepagoID property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        public static PagoPrepago CreatePagoPrepago(global::System.Int32 id, global::System.Int64 compraID, global::System.Int32 prepagoID, global::System.Int32 valor)
        {
            PagoPrepago pagoPrepago = new PagoPrepago();
            pagoPrepago.ID = id;
            pagoPrepago.CompraID = compraID;
            pagoPrepago.PrepagoID = prepagoID;
            pagoPrepago.Valor = valor;
            return pagoPrepago;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                OnCompraIDChanging(value);
                ReportPropertyChanging("CompraID");
                _CompraID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompraID");
                OnCompraIDChanged();
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PrepagoID
        {
            get
            {
                return _PrepagoID;
            }
            set
            {
                OnPrepagoIDChanging(value);
                ReportPropertyChanging("PrepagoID");
                _PrepagoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrepagoID");
                OnPrepagoIDChanged();
            }
        }
        private global::System.Int32 _PrepagoID;
        partial void OnPrepagoIDChanging(global::System.Int32 value);
        partial void OnPrepagoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Int32 _Valor;
        partial void OnValorChanging(global::System.Int32 value);
        partial void OnValorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoPrepago_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoPrepago_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoPrepago_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoPrepago_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("LasTacasModel.FK_PagoPrepago_Compra", "Compra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoPrepago_Prepago", "Prepago")]
        public Prepago Prepago
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prepago>("LasTacasModel.FK_PagoPrepago_Prepago", "Prepago").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prepago>("LasTacasModel.FK_PagoPrepago_Prepago", "Prepago").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Prepago> PrepagoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Prepago>("LasTacasModel.FK_PagoPrepago_Prepago", "Prepago");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Prepago>("LasTacasModel.FK_PagoPrepago_Prepago", "Prepago", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="PagoRedcompra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PagoRedcompra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PagoRedcompra object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="compraID">Initial value of the CompraID property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        /// <param name="transaccion">Initial value of the Transaccion property.</param>
        /// <param name="autorizacion">Initial value of the Autorizacion property.</param>
        public static PagoRedcompra CreatePagoRedcompra(global::System.Int32 id, global::System.Int64 compraID, global::System.String tipo, global::System.Int32 transaccion, global::System.Int32 autorizacion)
        {
            PagoRedcompra pagoRedcompra = new PagoRedcompra();
            pagoRedcompra.ID = id;
            pagoRedcompra.CompraID = compraID;
            pagoRedcompra.Tipo = tipo;
            pagoRedcompra.Transaccion = transaccion;
            pagoRedcompra.Autorizacion = autorizacion;
            return pagoRedcompra;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompraID
        {
            get
            {
                return _CompraID;
            }
            set
            {
                OnCompraIDChanging(value);
                ReportPropertyChanging("CompraID");
                _CompraID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompraID");
                OnCompraIDChanged();
            }
        }
        private global::System.Int64 _CompraID;
        partial void OnCompraIDChanging(global::System.Int64 value);
        partial void OnCompraIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Transaccion
        {
            get
            {
                return _Transaccion;
            }
            set
            {
                OnTransaccionChanging(value);
                ReportPropertyChanging("Transaccion");
                _Transaccion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Transaccion");
                OnTransaccionChanged();
            }
        }
        private global::System.Int32 _Transaccion;
        partial void OnTransaccionChanging(global::System.Int32 value);
        partial void OnTransaccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Autorizacion
        {
            get
            {
                return _Autorizacion;
            }
            set
            {
                OnAutorizacionChanging(value);
                ReportPropertyChanging("Autorizacion");
                _Autorizacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Autorizacion");
                OnAutorizacionChanged();
            }
        }
        private global::System.Int32 _Autorizacion;
        partial void OnAutorizacionChanging(global::System.Int32 value);
        partial void OnAutorizacionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoRedcompra_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoRedcompra_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoRedcompra_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("LasTacasModel.FK_PagoRedcompra_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("LasTacasModel.FK_PagoRedcompra_Compra", "Compra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Persona : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Persona object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="rUT">Initial value of the RUT property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="fechaRegistro">Initial value of the FechaRegistro property.</param>
        public static Persona CreatePersona(global::System.Int32 id, global::System.String rUT, global::System.String apellido, global::System.String nombre, global::System.DateTime fechaRegistro)
        {
            Persona persona = new Persona();
            persona.ID = id;
            persona.RUT = rUT;
            persona.Apellido = apellido;
            persona.Nombre = nombre;
            persona.FechaRegistro = fechaRegistro;
            return persona;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT
        {
            get
            {
                return _RUT;
            }
            set
            {
                OnRUTChanging(value);
                ReportPropertyChanging("RUT");
                _RUT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RUT");
                OnRUTChanged();
            }
        }
        private global::System.String _RUT;
        partial void OnRUTChanging(global::System.String value);
        partial void OnRUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            internal set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private global::System.DateTime _FechaRegistro;
        partial void OnFechaRegistroChanging(global::System.DateTime value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaNacimiento
        {
            get
            {
                return _FechaNacimiento;
            }
            set
            {
                OnFechaNacimientoChanging(value);
                ReportPropertyChanging("FechaNacimiento");
                _FechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNacimiento");
                OnFechaNacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaNacimiento;
        partial void OnFechaNacimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaNacimientoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_Compra_Persona", "Compra")]
        public EntityCollection<Compra> Compras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Compra>("LasTacasModel.FK_Compra_Persona", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Compra>("LasTacasModel.FK_Compra_Persona", "Compra", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LasTacasModel", Name="Prepago")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prepago : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Prepago object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="saldo">Initial value of the Saldo property.</param>
        public static Prepago CreatePrepago(global::System.Int32 id, global::System.Int32 saldo)
        {
            Prepago prepago = new Prepago();
            prepago.ID = id;
            prepago.Saldo = saldo;
            return prepago;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Saldo
        {
            get
            {
                return _Saldo;
            }
            set
            {
                OnSaldoChanging(value);
                ReportPropertyChanging("Saldo");
                _Saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Saldo");
                OnSaldoChanged();
            }
        }
        private global::System.Int32 _Saldo;
        partial void OnSaldoChanging(global::System.Int32 value);
        partial void OnSaldoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LasTacasModel", "FK_PagoPrepago_Prepago", "PagoPrepago")]
        public EntityCollection<PagoPrepago> Pagos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PagoPrepago>("LasTacasModel.FK_PagoPrepago_Prepago", "PagoPrepago");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PagoPrepago>("LasTacasModel.FK_PagoPrepago_Prepago", "PagoPrepago", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
